#!/bin/sh

current_date=$(date +"%Y%m%d")
mariadb-dump --host=${MARIADB_HOST} --user=${MARIADB_USER} --password=${MARIADB_PASSWORD} ${MARIADB_DATABASE} > /mnt/dump/${current_date}-${MARIADB_DATABASE}.sql