
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: secure-password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  mariadb-backup:
    build: ./cron-mariadb-backup
    command: crond -f -l 8
    environment:
      MARIADB_HOST : db
      MARIADB_DATABASE : mariadb
# Root en attendant de solutionner les privileges de connections à la base (%localhost)
      MARIADB_USER : root
      MARIADB_PASSWORD: mariadb
    volumes:
      - ./etc/periodic:/etc/periodic:ro
      - ./backups:/backups