
services:
    mariadb:
      image: mariadb
      restart: always
      environment:
        MARIADB_ROOT_PASSWORD: mariadb
        MARIADB_DATABASE: mariadb
        MARIADB_USER: mariadb
      volumes:
        - ./data:/var/lib/mysql
      ports:
        - 3306:3306

    mariadb-backup:
      build: ./mariadb-backup
      command: crond -f -l 8
      volumes:
        - ./etc/periodic:/etc/periodic:ro